# Generated by Django 4.0.2 on 2022-02-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='publication_date',
            field=models.DateField(null=True, verbose_name='publication date'),
        ),
    ]
